/*
 * PackagesOfFuture.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PaymentsApiController : ControllerBase
    { 
        /// <summary>
        /// Changes status of a payment
        /// </summary>
        /// <param name="id"></param>
        /// <param name="body">Details of payment status change</param>
        /// <response code="200">Success</response>
        /// <response code="204">When payment status was changed</response>
        /// <response code="400">When error regarding input occurred</response>
        [HttpPost]
        [Route("/Payments/change-status/{id}")]
        [ValidateModelState]
        [SwaggerOperation("PaymentsChangeStatusIdPost")]
        public virtual IActionResult PaymentsChangeStatusIdPost([FromRoute][Required]string id, [FromBody]ChangePaymentStatusDto body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Gets all payments
        /// </summary>
        /// <response code="200">When there are payments</response>
        /// <response code="404">If there are no payments</response>
        [HttpGet]
        [Route("/Payments")]
        [ValidateModelState]
        [SwaggerOperation("PaymentsGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<PaymentDto>), description: "When there are payments")]
        public virtual IActionResult PaymentsGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<PaymentDto>));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "[ {\n  \"amount\" : 9.301444243932576,\n  \"id\" : 2,\n  \"type\" : 7,\n  \"status\" : 3\n}, {\n  \"amount\" : 9.301444243932576,\n  \"id\" : 2,\n  \"type\" : 7,\n  \"status\" : 3\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<PaymentDto>>(exampleJson)
                        : default(List<PaymentDto>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
