/*
 * PackagesOfFuture.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AddressesApiController : ControllerBase
    { 
        /// <summary>
        /// Gets all addresses
        /// </summary>
        /// <response code="200">When addresses exist</response>
        /// <response code="404">When error regarding input occurred</response>
        [HttpGet]
        [Route("/Addresses")]
        [ValidateModelState]
        [SwaggerOperation("AddressesGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<AddressDto>), description: "When addresses exist")]
        public virtual IActionResult AddressesGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<AddressDto>));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "[ {\n  \"houseAndFlatNumber\" : \"houseAndFlatNumber\",\n  \"city\" : \"city\",\n  \"street\" : \"street\",\n  \"postalCode\" : \"postalCode\"\n}, {\n  \"houseAndFlatNumber\" : \"houseAndFlatNumber\",\n  \"city\" : \"city\",\n  \"street\" : \"street\",\n  \"postalCode\" : \"postalCode\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<AddressDto>>(exampleJson)
                        : default(List<AddressDto>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Registers a new package
        /// </summary>
        /// <param name="body">Representation of address to add</param>
        /// <response code="200">Success</response>
        /// <response code="204">When package was registered</response>
        /// <response code="400">When error regarding input occurred</response>
        [HttpPost]
        [Route("/Addresses")]
        [ValidateModelState]
        [SwaggerOperation("AddressesPost")]
        public virtual IActionResult AddressesPost([FromBody]AddAddressDto body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            throw new NotImplementedException();
        }
    }
}
