name: PackagesOfFuture.WebUI-PR

on:
  pull_request:
    branches: [ master ]
    paths: 
      - 'PackagesOfFuture.WebUI/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'PackagesOfFuture.WebUI'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Test
        run: npm run test-headless:ci
